import type { SiteControls } from "@/types";

export const DEFAULT_SITE_CONTROLS: SiteControls = {
  banners: [
    {
      id: "the-tea-lineup",
      title: "The Tea Lineup. Pick Your Sip.",
      subtitle: "Whole flowers, single-origin leaves, authentic kadak chai.",
      ctaText: "Shop The Lineup",
      ctaLink: "/#shop",
      desktopSrc: "/banners/the-tea-lineup-pick-your-sip.png",
      mobileSrc: "/banners/the-tea-lineup-pick-your-sip.png",
      enabled: true,
      order: 0,
    },
    {
      id: "sip-happens",
      title: "Sip Happens. Pick Your Mood.",
      subtitle: "From morning hustle to evening calm — tea made for real daily rituals.",
      ctaText: "Explore Blends",
      ctaLink: "/collections",
      desktopSrc: "/banners/sip-happens-pick-your-mood.png",
      mobileSrc: "/banners/sip-happens-pick-your-mood.png",
      enabled: true,
      order: 1,
    },
    {
      id: "butterfly-pea-bloom",
      title: "Bloom in Every Sip.",
      subtitle: "100% Natural • Caffeine Free • Turns Sapphire to Violet with Lemon",
      ctaText: "Explore Butterfly Pea",
      ctaLink: "/products/butterfly-pea",
      desktopSrc: "/banners/butterfly-pea-bloom-in-every-sip.png",
      mobileSrc: "/banners/butterfly-pea-bloom-in-every-sip.png",
      enabled: true,
      order: 2,
    },
    {
      id: "hibiscus-beautiful",
      title: "Make Time for Beautiful.",
      subtitle: "Whole ruby hibiscus calyces brewing tart, antioxidant-rich crimson.",
      ctaText: "Shop Hibiscus",
      ctaLink: "/products/hibiscus",
      desktopSrc: "/banners/hibiscus-make-time-for-beautiful.png",
      mobileSrc: "/banners/hibiscus-make-time-for-beautiful.png",
      enabled: true,
      order: 3,
    },
    {
      id: "lemongrass-less-scroll",
      title: "Less Scroll. More Sip.",
      subtitle: "Zesty sun-dried lemongrass stalks for an invigorating citrus lift.",
      ctaText: "Discover Lemongrass",
      ctaLink: "/products/lemongrass",
      desktopSrc: "/banners/lemongrass-less-scroll-more-sip.png",
      mobileSrc: "/banners/lemongrass-less-scroll-more-sip.png",
      enabled: true,
      order: 4,
    },
    {
      id: "properly-kadak-chai",
      title: "Properly Kadak Chai.",
      subtitle: "Strong Assam CTC blended for bold morning chai with milk & adrak.",
      ctaText: "Shop Kadak Chai",
      ctaLink: "/products/gold-tea",
      desktopSrc: "/hero/hero-desktop.png",
      mobileSrc: "/hero/hero-mobile.png",
      enabled: true,
      order: 5,
    },
  ],
  products: [
    {
      id: "butterfly-pea",
      name: "Butterfly Pea Flower Tea",
      category: "herbal-flower",
      price: 99,
      compareAtPrice: 129,
      frontImage: "/hero/butterfly-pea-50g-jar-front.png",
      backImage: "/products/butterfly-pea-50g-jar-back.jpg",
      isBestSeller: true,
      isPopularPick: true,
      enabled: true,
      order: 0,
    },
    {
      id: "hibiscus",
      name: "Hibiscus Flower Tea",
      category: "herbal-flower",
      price: 119,
      compareAtPrice: 149,
      frontImage: "/hero/hibiscus-50g-jar-front.png",
      backImage: "/products/hibiscus-50g-jar-back.jpg",
      isBestSeller: true,
      isPopularPick: true,
      enabled: true,
      order: 1,
    },
    {
      id: "darjeeling-green",
      name: "Darjeeling Whole Leaf Green Tea",
      category: "green-tea",
      price: 149,
      compareAtPrice: 189,
      frontImage: "/hero/darjeeling-100g-jar-front.png",
      backImage: "/products/darjeeling-100g-jar-back.jpg",
      isBestSeller: true,
      isPopularPick: false,
      enabled: true,
      order: 2,
    },
    {
      id: "gold-tea",
      name: "Assam Gold CTC Tea",
      category: "chai",
      price: 399,
      compareAtPrice: 449,
      frontImage: "/hero/gold-250g-pouch-front.png",
      backImage: "/products/gold-250g-pouch-back.jpg",
      isBestSeller: true,
      isPopularPick: true,
      enabled: true,
      order: 3,
    },
    {
      id: "lemongrass",
      name: "Lemongrass Herbal Tea",
      category: "herbal-flower",
      price: 99,
      compareAtPrice: 129,
      frontImage: "/hero/lemongrass-50g-jar-front.png",
      backImage: "/products/lemongrass-50g-jar-back.jpg",
      isBestSeller: false,
      isPopularPick: true,
      enabled: true,
      order: 4,
    },
  ],
  collections: [
    {
      id: "herbal-flower",
      name: "Whole Flower & Herbal Teas",
      description: "Naturally caffeine-free, whole sun-dried botanicals.",
      enabled: true,
      order: 0,
    },
    {
      id: "green-tea",
      name: "Darjeeling Single-Origin",
      description: "Delicate spring flush whole leaves from misty Himalayan slopes.",
      enabled: true,
      order: 1,
    },
    {
      id: "chai",
      name: "Authentic Assam Kadak Chai",
      description: "Bold brisk CTC crafted to cut through boiling milk and ginger.",
      enabled: true,
      order: 2,
    },
  ],
  sections: [
    {
      id: "hero",
      label: "Hero Campaign Banners",
      heading: "The Tea Lineup. Pick Your Sip.",
      subheading: "Storefront Campaign Banners",
      ctaText: "Shop Now",
      ctaLink: "/#shop",
      enabled: true,
      order: 0,
    },
    {
      id: "trust-strip",
      label: "Value Highlights Strip",
      heading: "The TMUG Promise",
      subheading: "100% Whole Botanicals • Zero Dust",
      enabled: true,
      order: 1,
    },
    {
      id: "collections",
      label: "Shop by Collection",
      heading: "Shop by Collection",
      subheading: "Curated categories for every tea mood",
      ctaText: "Explore Blends",
      ctaLink: "/collections",
      enabled: true,
      order: 2,
    },
    {
      id: "best-sellers",
      label: "Best Sellers (50/50 Showcase)",
      heading: "Best Sellers",
      subheading: "The teas everyone keeps reordering.",
      ctaText: "View Details",
      enabled: true,
      order: 3,
    },
    {
      id: "open-reveal",
      label: "Interactive Box Reveal",
      heading: "Open Your Tea Ritual",
      subheading: "Tap to open the TMUG collector’s box",
      ctaText: "Open TMUG Box",
      enabled: true,
      order: 4,
    },
    {
      id: "why-tmug",
      label: "Why TMUG (4 Pillars)",
      heading: "Tea should feel exciting, not ordinary.",
      subheading: "The TMUG Difference",
      ctaText: "Discover Our Story",
      ctaLink: "/about",
      enabled: true,
      order: 5,
    },
    {
      id: "real-tea",
      label: "Made With Real Tea",
      heading: "Made with real tea.",
      subheading: "Pure botanicals you can see and trust",
      ctaText: "Taste the Difference",
      ctaLink: "/#shop",
      enabled: true,
      order: 6,
    },
    {
      id: "tea-story",
      label: "The TMUG Ritual Moments",
      heading: "More than just a cup of tea.",
      subheading: "From morning kickstart to midnight calm",
      ctaText: "Start Brewing",
      ctaLink: "/#shop",
      enabled: true,
      order: 7,
    },
    {
      id: "rituals-recipes",
      label: "Rituals & Creative Recipes",
      heading: "Rituals & Recipes",
      subheading: "Community inspirations and creative dishes",
      ctaText: "Explore Creations",
      enabled: true,
      order: 8,
    },
    {
      id: "lifestyle",
      label: "Moments That Linger",
      heading: "Made for moments that linger.",
      subheading: "Playful editorial moodboard and stickers",
      ctaText: "Shop Tea",
      ctaLink: "/#shop",
      enabled: true,
      order: 9,
    },
    {
      id: "brand-proof",
      label: "Honest Quality Proof",
      heading: "Tea worth talking about.",
      subheading: "No corporate jargon, just honest tea",
      enabled: true,
      order: 10,
    },
    {
      id: "customer-love",
      label: "Customer Reviews",
      heading: "Good tea deserves good company.",
      subheading: "Real words from our sipping community",
      ctaText: "Share Feedback",
      enabled: true,
      order: 11,
    },
    {
      id: "stores",
      label: "Available Where You Shop",
      heading: "Available where you shop.",
      subheading: "Amazon Brand Store & WhatsApp Concierge",
      ctaText: "Shop on Amazon",
      enabled: true,
      order: 12,
    },
    {
      id: "final-cta",
      label: "Final Conversion CTA",
      heading: "Ready to make tea more fun?",
      subheading: "Start your ritual with fresh doorstep delivery",
      ctaText: "Shop TMUG",
      ctaLink: "/#shop",
      enabled: true,
      order: 13,
    },
  ],
};
